INSERT INTO strategicareas VALUES (NULL,'Gestión de Riesgos y Desastres')
,(NULL,'SALUD, AGUA Y SANEAMIENTO')
,(NULL,'INCLUSIÓN SOCIAL')
,(NULL,'FORTALECIMIENTO DEL VOLUNTARIADO Y SECCIONALES')
,(NULL,'Fortalecimiento y Modernización Institucional')
,(NULL,'Sostenibilidad ')
,(NULL,'DIRECCIÓN GENERAL')
,(NULL,'Garantizar el óptimo funcionamiento y desarrollo institucional a través de la aplicación de políticas, estrategias, normas y procedimientos.  ')
,(NULL,'PLANIFICACIÓN Y DESARROLLO INSTITUCIONAL')
,(NULL,'Generar información y herramientas útiles y oportunas que contribuya al desarrollo institucional y a la trasferencia de conocimientos.')
,(NULL,'Mejorar la gestión de seguridad para minimizar los riesgos enfrentados por los miembros de la institución. ')
,(NULL,'CENTRO DE SANGRE')
,(NULL,'DEPARTAMENTO JURÍDICO')
,(NULL,'ASESORIA ESTRATÉGICA')
,(NULL,'RELACIONES PUBLICAS Y COMUNICACIONES')
,(NULL,'COMUNICACIONES ')
,(NULL,'DIRECCIÓN DE GESTIÓN DE RECURSOS HUMANOS')
,(NULL,'DEPARTAMENTO GESTIÓN DEL TALENTO HUMANO')
,(NULL,'AUDITORIA INTERNA')
,(NULL,'Disminuir los riesgos institucionales para el logro de los objetivos estratégicos  ')
,(NULL,'DIRECCIÓN DE OPERACIONES DE EMERGENCIAS')
