insert into measurementunits VALUES(NULL,'planes',NULL)
,(NULL,'convenios',NULL)
,(NULL,'Vehículos  4x4 ambulancias',NULL)
,(NULL,'Radios digitales',NULL)
,(NULL,'Cantidad de nuevas repetidoras',NULL)
,(NULL,'% de Informes oportunos y de calidad',NULL)
,(NULL,'Cantidad de informes estadísticos oportunos y de calidad',NULL)
,(NULL,'kits',NULL)
,(NULL,'comunidades',NULL)
,(NULL,'escuelas',NULL)
,(NULL,'voluntarios/personal  capacitados',NULL)
,(NULL,'Familias',NULL)
,(NULL,'seccionales',NULL)
,(NULL,'Servicios',NULL)
,(NULL,'% de incremento en la satisfacción en atención ',NULL)
,(NULL,'Personas capacitadas',NULL)
,(NULL,'Personal de planta en horas diurnas',NULL)
,(NULL,'VICITS',NULL)
,(NULL,'Cantidad de empresas',NULL)
,(NULL,'Numero de nuevos donantes',NULL)
,(NULL,'Porcentaje de incremento de satisfacción',NULL)
,(NULL,'Numero de unidades',NULL)
,(NULL,'Numero de pruebas realizadas',NULL)
,(NULL,'Porcentaje de participación en el Comité',NULL)
,(NULL,'Voluntarios ',NULL)
,(NULL,'NNAJ',NULL)
,(NULL,'Proyectos ',NULL)
,(NULL,'programa',NULL)
,(NULL,'% de voluntarios',NULL)
,(NULL,'Seccionales ',NULL)
,(NULL,'%',NULL)
,(NULL,'Cantidad',NULL)
,(NULL,'Decreto',NULL)
,(NULL,'Cantidad de casos',NULL)
,(NULL,'Propuesta',NULL)
,(NULL,'Politica',NULL)
