INSERT INTO indicatorpo values (NULL,'Cantidad de  planes elaborados e implementados del sistema de planificación a desastres ',NULL)
,(NULL,'Cantidad de documentos que fortalezcan la coordinación y el trabajo en gestión de riesgos con otras instituciones publicas y privadas',NULL)
,(NULL,'Cantidad de vehículos (Ambulancias 4x4) puestos a disposición a las seccionales para responder a las emergencias de sus zonas de cobertura',NULL)
,(NULL,'Cantidad de radios digitales con los que cuentan las seccionales para conectarse con el sistema nacional',NULL)
,(NULL,'Cantidad de nuevas repetidoras disponibles para CRS y tener una cobertura del 90% del territorio nacional.',NULL)
,(NULL,'Cantidad de informes oportunos y con calidad que se emiten de situación a nivel nacional, informes especiales de desastres y crisis o en forma previa con alertas ',NULL)
,(NULL,'Cantidad de Informes de tendencias estadísticas oportunos y de calidad que se emiten mensuales de tendencias estadísticas sobre emergencias y desastres es emitido y socializado a autoridades claves de la institución ',NULL)
,(NULL,'Inventario de insumos humanitarios  para 1500 familias están disponibles y reemplazados cuando estos son usados.',NULL)
,(NULL,'Cantidad de comunidades vulnerables que crean o actualizan sus planes comunales de preparación y respuesta a emergencias y desastres',NULL)
,(NULL,'Cantidad de escuelas  vulnerables crean o actualizan sus planes escolares de preparación y respuesta a emergencias y desastres con el apoyo de las Seccionales de la CRS',NULL)
,(NULL,'# de voluntarios/personal capacitados.',NULL)
,(NULL,'# de familias intervenidas',NULL)
,(NULL,'# de seccionales ejecutan acciones de protección al medioambiente.',NULL)
,(NULL,'# de servicios de calidad brindados                                                               ',NULL)
,(NULL,'Incremento porcentual de la satisfacción de la atención a los usuarios.',NULL)
,(NULL,'# personal capacitado',NULL)
,(NULL,'# de paramédicos contratados de planta en horas diurnas.',NULL)
,(NULL,'# de VICITIS cuentan con personal capacitado, con recursos de información y educación para la salud y con dotación de condones en cantidad y calidad necesaria para el desarrollo de sus actividades.',NULL)
,(NULL,'Cantidad de nuevas empresas e instituciones que donan',NULL)
,(NULL,'Cantidad de nuevos donantes',NULL)
,(NULL,'Porcentaje de incremento de la satisfacción de donantes respecto a la atención recibida',NULL)
,(NULL,'Unidades de sangre colocadas en la red nacional',NULL)
,(NULL,'Cantidad de Pruebas de laboratorio',NULL)
,(NULL,'Participación con la red de hospitales nacionales',NULL)
,(NULL,'Cantidad de voluntarios sensibilizados en inclusión social  ',NULL)
,(NULL,'Cantidad de voluntarios capacitados y fortalecidos en temáticas de reducción de violencia y cultura de paz',NULL)
,(NULL,'Cantidad de comunidades resilientes, fortalecidas en cultura de paz ',NULL)
,(NULL,'Cantidad de proyectos que implementan componentes del Programa con énfasis en los grupos vulnerables prioritarios ',NULL)
,(NULL,'Número de programas definidos por cuerpo filial y órganos de gobierno.',NULL)
,(NULL,'%  de voluntarios formados/capacitados      ',NULL)
,(NULL,'Numero de seccionales con mejoras en su infraestructura/ mobiliario/equipo ',NULL)
,(NULL,'% de incremento real del voluntariado',NULL)
,(NULL,'% de voluntarios evaluados',NULL)
,(NULL,'% de voluntarios que participan activamente en actividades de riesgo, salud e inclusión social',NULL)
,(NULL,'% de voluntarios que se les ha dado reconocimiento',NULL)
,(NULL,'% de incremento  de los ingresos de Miembros Contribuyentes, Eventos y Capacitación ',NULL)
,(NULL,'% de implementación',NULL)
,(NULL,'% de reducción de costos',NULL)
,(NULL,'% de incremento de los recursos por las acciones del plan',NULL)
,(NULL,'Unidad creada',NULL)
,(NULL,'% de la sistematización ',NULL)
,(NULL,'% de implementación de la Intranet ',NULL)
,(NULL,'% de inversión en infraestructura, mobiliario y equipo; según plan de mercadeo',NULL)
,(NULL,'% de implementación del plan ',NULL)
,(NULL,'% actualización de los procesos ',NULL)
,(NULL,'Actualización del decreto',NULL)
,(NULL,'Cantidad de casos resueltos a traves de intervención institucional con otros actores ',NULL)
,(NULL,'Cantidad de propuestas comerciales',NULL)
,(NULL,'Politica elaborada',NULL)
,(NULL,'Porcentaje de recuperación de costos en cada proyecto',NULL)
